### ISSUE TITLE
CH RAD-Order ServiceRequest.supportingInfo:caveats (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#10]
ch.fhir.ig.ch-rad-order#0.1.0 /StructureDefinition-ch-rad-order-servicerequest.html

Könnte man die Caveats als Observation mit category und code abbilden, anstelle der Condition mit einer extra Extension für den 'CH RAD-Order Caveat Type'?

Michaela Ziegler, ahdis ag

**Comment by JBleuer** [comment]
After discusssion with @Michaela: We let it as ist. Argumentation see attachmen
[Caveats als Conditioin_Begruendung.pdf](https://github.com/hl7ch/ch-rad-order/files/7608055/Caveats.als.Conditioin_Begruendung.pdf)
t.

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
