### ISSUE TITLE
Questionnaire: Selbstzahler (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#11]
ch.fhir.ig.ch-rad-order#0.1.0 /questionnaire.html

Why do you have to give the family name and the given name again for self-pay (Selbstzahler)? Where should this be mapped to (Patient already mapped)?

Michaela Ziegler, ahdis ag

**Comment by JBleuer** [comment]
Der Use Case:

Leistung des HP wird von Versicherung nicht gedeckt; bezahtl wird sie aber nich vom Patienten sondern Vater, Freund etc.:

Läuft unter "Selbstzahler", auch wenn die Rechnung in diesem Fall nicht vom Patient selbst bezahlt wird.

Vorschlag zur Abbildung:

Die Resource Coverage hat im Original:

Diese related Person ist in CH ORF Coverage nicht mehr drin.

Man müsste wohl ei CH Core Related Person machen.
CH Core Related Person  in CH ORF Coverage wieder einfügen.

Hinweis auf Gestaltung des Questionnaires: Auswahlbox: Selbst, Andere Person.
Sebst --> Population mit Pat Name, Adresse etc.; Andere Person: Leer für händische Eingabe.
Umsetzung in ORF

**Comment by JBleuer** [comment]
Wird bei orf abgehandelt
