### ISSUE TITLE
Questionnaire - XML and JSON representation not shown (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#13]
ch.fhir.ig.ch-rad-order#0.1.0 /questionnaire.html

It would be nice if on the questionnaire menu/tab you would also have the XML and JSON representation available as in http://fhir.ch/ig/ch-rad-order/Questionnaire-QuestionnaireRadiologyOrder.html 

Oliver Egger, ahdis

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
