### ISSUE TITLE
Questionnaire Text in German, ValueSets in english (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#14]
ch.fhir.ig.ch-rad-order#0.1.0 /questionnaire.html

The questionnaire is defined with german text descriptions, CodeSystem/ValueSet is however RequestedService is however in english:

http://fhir.ch/ig/ch-rad-order/CodeSystem-ch-rad-order-requested-service.html

Propose that the german translation will be added.
Need to add guidance if there will be different questionnaires by language or one questionnaire with all languages included (possibly something which should be defined also in CH-ORF)

Oliver Egger, ahdis ag

**Comment by JBleuer** [comment]
Value Set changed to:
* #RequestForPrecedentReport "Befundbericht früherer Untersuchung(en)"
* #RequestForPrecedentReportAndImages "Bilder und Befundberichte früherer Untersuchung(en)"
* #ImagingRequest "Bildgebenden Diagnostik"
* #RadIntervention "Interventionelle Radiologie"
* #SecondOpinion "Zweitmeinung"
* #ImagingRequestWithIntervention "Bildgebende Diagnostik und Intervention"
* #RemoteReporting "Fernbefundung"

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
