### ISSUE TITLE
Questionnaire (Pedro dos Santos - Die Post CH)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#15]
ch.fhir.ig.ch-rad-order#0.1.0 /questionnaire.html

caveat.renalInsufficiency.creatinine.quantity	Wert (µmol/l)

According to SI/UCUM units, liters should be expressed in capital letter --> µmol/L

REF: https://hl7.org/fhir/us/core/2017Jan/ValueSet-us-core-ucum.html

Pedro dos Santos - Die Post CH

**Comment by Psantos** [comment]
Same issue affects multiple entries:
- caveat.bloodCoagulation.platelets.quantity	                        Wert (10^3/µl)	
- caveat.renalInsufficiency.creatinineClearance.quantity	Wert (ml/min)
- caveat.renalInsufficiency.creatinine.quantity	Wert                         (µmol/l)

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
