### ISSUE TITLE
qa.html Validation Errors (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#16]
ch.fhir.ig.ch-rad-order#0.1.0 /qa.html - Validation Errors

The Quality Assurance Page of the IG Publisher shows errors for the example artifacts
- Bundle.entry:Composition: minimum required = 1, but only found 0 (from http://fhir.ch/ig/ch-rad-order/StructureDefinition/ch-rad-order-document)
- Composition.section:orderReferral.entry:QuestionnaireResponse: minimum required = 1, but only found 0 (from http://fhir.ch/ig/ch-rad-order/StructureDefinition/ch-rad-order-composition)
- The value provided (http://www.radlex.org::RID10345) is not in the options value set in the questionnaire
- Extension http://fhir.ch/ig/ch-rad-order/StructureDefinition/ch-rad-order-composition is for type StructureDefinition[http://fhir.ch/ig/ch-rad-order/StructureDefinition/ch-rad-order-composition], but the Bundle.entry.resource element has type Resource
- Resource id/url mismatch: null/http://fhir.ch/ig/ch-rad-order/Questionnaire/QuestionnaireRadiologyOrder

Oliver Egger, ahdis

**Comment by JBleuer** [comment]
issues fixed in the course of other changes

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
