### ISSUE TITLE
CH RAD-Order ImagingStudy - Missing Definition in Questionnaire (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#17]
ch.fhir.ig.ch-rad-order#0.1.0 /StructureDefinition-ch-rad-order-imagingstudy.html

ImagingStudy is referred to by the ServiceRequest, however the questionnaire has no part where such a reference to the ImagingStudy could be added.

If a ImagingStudy is provided it should also be explained in the implementation Guide that the ImagingStudy itself is not contained and needs to be exchanged in another way depending on the situation. 

Oliver Egger, ahdis

**Comment by JBleuer** [comment]
@oliveregger @ziegm 
Added dicom study series instance uid and sop instance uid in questionnaire

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
