### ISSUE TITLE
Profile for Structured Data (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#18]
ch.fhir.ig.ch-rad-order#0.1.0 / Profile for Structured Data only

Currently Questionnaire and QuestionnaireResponse are required for CH ORF and CH RAD Order. It would be helpful to have also a document definition for the RAD Order with only the structured information provided. This would be useful for validation and maybe also for systems claiming conformance for working with orders without relying on the Questionnaire/QuestionnairerResponse?

Oliver Egger, ahdis ag

**Comment by JBleuer** [comment]
Fixed in orf (Cardinality for Questionnaire and QR in Composition set to 0..1. Explanation in home.
Explantion in home also added in RAD-Order and eTOC

**Comment by JBleuer** [comment]
Abgehandelt bei eToc
