### ISSUE TITLE
Formulare Abschnitt Caveats / Vorbehalte  (Moritz Strickler, Clarisse Loechleiter, Post CH Kommunikation AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#19]
ch.fhir.ig.ch-rad-order#0.1.0 /

Die Vorbehalte / Caveats sollten nicht als Boolean sondern je Caveat als Liste beantwortet werden können. Die Liste soll die folgenden Auswahlen enthalten: JA/Nein/Nicht gefragt.

Moritz Strickler, Clarisse Loechleiter, Post CH Kommunikation AG

**Comment by JBleuer** [comment]
Nach Rücksprache mit T. Frauenfelder: 3 Antworten Ja/Nein/Nicht gefragt, default "Nicht gefragt"

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
