### ISSUE TITLE
PDF als orginialRepresentation im ch-rad-order aufnehmen

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-rad-order#2]
Müssen wir noch hinzufügen:

The basic principle is to capture data on order placer site by forms (FHIR questionnaires) and to render the resulting QuestionnaireResponse to a PDF/A document

**Comment by ziegm** [comment]
Für die Entries in der Composition (z.B. ServiceRequest, Questionnaire) müssen wir noch eine Section mit **Code (TBD)** definieren, so dass wir die Composition.section:originalRepresentation einführen können (siehe [Bsp.](http://fhir.ch/ig/ch-core/StructureDefinition-ch-core-composition-epr.html) im CH Core).
