### ISSUE TITLE
Mehrere Bildgebendeverfahren in einem Auftrag (Moritz Strckler, Clarisse Lochleiter, Post CH Kommunikations AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#20]
ch.fhir.ig.ch-rad-order#0.1.0 /

Es sollte möglich sein, mehrere Bildgebendeverfahren in einem Auftrag zu Beauftragen. Mit dem aktuellen Vorschlag kann jeweils nur ein Bildgebendesverfahren beauftragt werden und das Formular muss für jedes Bildgebendesverfahren erneut ausgefüllt werden. Bspw. könnte die Gruppe "Bildgebendesverfahren" im Formular wiederholbar sein. 

Moritz Strckler, Clarisse Lochleiter, Post CH Kommunikations AG

**Comment by JBleuer** [comment]
Meherer bildgebende Verfahren beinhalten
   - ev. mehere Radiologen und
   - ev. meherer Appointments 
                    === > Es wird kompliziert und unübersichtlich.

Es ist auch fraglich, ob ein empfangendes System das handeln kann.

**Comment by JBleuer** [comment]
After discussion with Moritz and Clarisse: We let it as is.

**Comment by JBleuer** [comment]
Mail from Moritz: 
Hallo Jürg

Danke für die Erläuterung!


Unsere Anforderungen sind dadurch abgedeckt.

LG Moritz

 

Von: Juerg Bleuer <bleuer@healthevidence.ch>
Gesendet: Dienstag, 23. November 2021 15:40
An: Strickler Moritz, KS3 <moritz.strickler@post.ch>
Betreff: Re: WG: Mehrere Bildgebendeverfahren in einem Auftrag (Moritz Strckler, Clarisse Lochleiter, Post CH Kommunikations AG) #20

 

Lieber Moritz

Dia Angaben zum gewünschten bidlgebenden Verfahren gibt man hier ein:

Imgaging Region gibt an, welche Regionen geröngt werden sollen (Bsp. Oberbauch /Unterbauch)

Der Imaging Focus gibt an, was in dieser REgion von Interesse ist (z.B. Leber)

Das entspricht doch eueren Anforderungen, oder?

Der Punkt "mehrere Untersuchungen" (Z.B. Rx und Ultraschall) ist davon aber unabhängig. Daür bräuchte es 2 Orders; zumindest vorderhand möchten wir das so lassen; Begründung s. frühere Mail.

LG Juerg

 

 

Am 17.11.21 um 14:46 schrieb moritz.strickler@post.ch:

    Lieber Jürg

     

    Clarisse hatte heute noch einen Austausch mit einem MTR und hat den Anwendungsfall nochmals verifiziert.

    Die Mindestanforderung unsererseits wäre, dass nebst dem Auftrag z.B. «Röntgen» via Textfeld präzisiert werden kann, welche Regionen geröntgt werden müssen.

     

    Wäre das eine Möglichkeit?

     

    Liebe Grüsse

    Moritz

     

    Von: Loechleiter Clarisse, KS3 <clarisse.loechleiter@post.ch>
    Gesendet: Mittwoch, 17. November 2021 14:40
    An: Strickler Moritz, KS3 <moritz.strickler@post.ch>
    Betreff: AW: Mehrere Bildgebendeverfahren in einem Auftrag (Moritz Strckler, Clarisse Lochleiter, Post CH Kommunikations AG) #20

     

    Hallo Moritz,

     

    Mehrere Untersuchungen sind wünschenswert. Sie werden aber im gleichen Termin mit dem gleichen Radiologen gemacht.

    Zum Beispiel wenn jemand stürzt braucht man :

    1.      Röntgen Knie Links

    2.      Röntgen Handgelenk Links

     

    Das sind sehr häufige Fälle und ist in den Systemen, die Order Entry managen verfügbar und das kann man in den  Schnittstellen in HL7 v2 ORM gut verwalten.

    Wenn ein Arzt schon ein Kode (LOINC) aussuchen muss, möchte er dann auch seine Untersuchungen finden.

     

    Sonst muss der Arzt mindestens:

    Röntgen auswählen können und in einem Text Feld Knie Links + Handgelenk Links eingeben können.

     

    Zwei Untersuchungen an verschiedene Tage ist nicht notwendig. Da kann der Arzt, 2 Anfragen machen.

     

    Beste Grüsse,

     

    Clarisse

     

     

    Von: Juerg Bleuer <bleuer@healthevidence.ch>
    Gesendet: Dienstag, 16. November 2021 20:14
    An: Strickler Moritz, KS3 <moritz.strickler@post.ch>
    Betreff: Re: Mehrere Bildgebendeverfahren in einem Auftrag (Moritz Strckler, Clarisse Lochleiter, Post CH Kommunikations AG) #20

     

    LIeber Moritz

    Darf ich noch einmal  mit untenstehender Frage an dich gelangen:

    LG Juerg

     

    Am 08.11.21 um 19:34 schrieb Juerg Bleuer:

        Lieber Moritz

        Du hast in deinem Issue vorgeschlagen, mehrere Bildgebungsverfahren im gleichen Auftrag abbilden zu können.

        Ichh sehe den Bedarf dafür; aus folgenden Gründen haben wir das bis jetzt nicht vorgesehen:

        - Meherer bildgebende Verfahren beinhalten

           - ev. mehere Radiologen und

           - ev. meherer Appointments 

                            === > Es wird kompliziert und unübersichtlich.

        Es ist auch fraglich, ob ein empfangendes System das handeln kann.

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
