### ISSUE TITLE
Frage zu Abschnitt "Kopienempfänger" im Formular (Moritz Strickler, Clarisse Loechleiter, Post CH Kommunkation AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#21]
ch.fhir.ig.ch-rad-order#0.1.0 /

Ist der Kopienempfänger als Empfänger des Auftrags oder nur als Empfänger der Resultate gedacht?

Moritz Strickler, Clarisse Loechleiter, Post CH Kommunkation AG

**Comment by JBleuer** [comment]
Empfänger von Auftrag und Resultat
