### ISSUE TITLE
Questionnaire (Pero Grgic / eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#23]
ch.fhir.ig.ch-rad-order#0.1.0 /questionnaire.html

Beim Text zu caveat.drugPrescription steht "z.B. Metformin". Jedoch hat es Value Set nur den Code für Medformin. 
Vorschlag: caveat.drugPrescription zu boolian machen mit Ja/Nein und das "z.B." löschen oder Substanz Value Set von eMedication übernehmen und ein Option Set hinzufügen.

Pero Grgic / eHealth Suisse

**Comment by JBleuer** [comment]
According to T. Frauenfelder, two drugs are relevant: Metformin and Betablockers.
Added therefore Betablocker to VS.

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
