### ISSUE TITLE
Errors in QA: The value provided is not in the options value set in the questionnaire

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-rad-order#3]
Errors in QA for QuestionnaireResponse-QuestionnaireResponseRadiologyOrder.json
- The value provided (http://www.radlex.org::RID10345) is not in the options value set in the questionnaire
- The value provided (http://www.radlex.org::RID1243) is not in the options value set in the questionnaire
- The value provided (http://www.radlex.org::RID2468) is not in the options value set in the questionnaire

This errors cause the consequence errors in:
- Composition-CompositionRadiologyOrder.json
- Bundle-DocumentRadiologyOrder.json

Known Issue, see discussion on [Zulip](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Questionnaire.3A.20Value.20not.20in.20value.20set). Will be fixed as soon as possible.

**Comment by JBleuer** [comment]
Problem is still there; has to be solved by IG-Publisher developpers: @ziegm: How to proceed ?

**Comment by ziegm** [comment]
> Problem is still there; has to be solved by IG-Publisher developpers: @ziegm: How to proceed ?

@JBleuer: My recommendation would be to take up the discussion in Zulip again and ask specifically whether the issue might be resolved in the near future.

**Comment by JBleuer** [comment]
issues fixed in the course of other changes

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
