### ISSUE TITLE
Questionnaire Radiology Order (Oliver Egger)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#36]
ch.fhir.ig.ch-rad-order#1.0.0 /Questionnaire-QuestionnaireRadiologyOrder.html

Diabetes mellilus has no default value

Oliver Egger

**Comment by oliveregger** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/2414516/155205189-41cd772f-f42e-464f-a0c8-a04929863874.png">

**Comment by oliveregger** [comment]
https://test.ahdis.ch/matchbox/#/questionnaire/QuestionnaireRadiologyOrder

**Comment by pjolo** [comment]
Checked and ok
