### ISSUE TITLE
providing DICOM Series Instance UID leads to an error in validation after mapping 

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-rad-order#37]
providing DICOM Series Instance UID leads to an error in the mapping:

error L1: ImagingStudy.series.modality: minimum required = 1, but only found 0 (from http://hl7.org/fhir/StructureDefinition/ImagingStudy) Bundle.entry[20].resource.ofType(ImagingStudy).series[0]

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/2414516/155205872-638653d4-2806-407d-8463-63654d4e8530.png">

**Comment by JBleuer** [comment]
As discussed in team: We ad additional code in value set in order to allow attaching dicom files with missing entry for modality.
