### ISSUE TITLE
Changelog (Oliver Egger)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#38]
ch.fhir.ig.ch-rad-order#1.0.0 /changelog.html

Link zu Issues funktionieren nicht: Link im Browser zeigt an, zum Beispiel:
https://github.com/hl7chhttp://build.fhir.org/ig/hl7ch/ch-orf/issues/19

sollte https://github.com/hl7ch/ch-orf/issues/19 sein

Oliver Egger

**Comment by pjolo** [comment]
Checked and ok
