### ISSUE TITLE
Details zur Bildgebung gibt Fehler (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#39]
ch.fhir.ig.ch-rad-order#1.0.0 /Questionnaire-QuestionnaireRadiologyOrder.html

Falls nur Details zum Bildgebenden Verfahren ausgewählt wird, gibt es einen Fehler:

Extracted FHIR Resources not valid
error L1: prr-1: 'orderDetail SHALL only be present if code is present' Rule 'orderDetail SHALL only be present if code is present' Failed Bundle.entry[3].resource.ofType(ServiceRequest)

Dies geschieht wenn man 'Bildgebendes Verfahren' nicht angegeben hat. Dies ist aber eine Voraussetzung für die Details und sollte entsprechend im Formular getestet (oder Details nur enabled werden wenn Bildgebendes Verfahren angegeben wird).

 

Oliver Egger, ahdis

**Comment by JBleuer** [comment]
Added a default value to "Bildgebendes Verfahren"; --> this item will never be empty

**Comment by pjolo** [comment]
Good
