### ISSUE TITLE
Change type of item 'previousResults.attachment' (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#4]
ch.fhir.ig.ch-rad-order#0.1.0 /questionnaire.html

The correct [type](https://www.hl7.org/fhir/valueset-item-type.html) of the item 'previousResults.attachment' would be 'attachment' instead of 'string'.
The subdivision into title and data is not necessary, because the data type [attachment](http://hl7.org/fhir/R4/datatypes.html#Attachment) already includes these posibilities.

Need to be changed in Questionnaire/QuestionnaireResponse and added in StructureMap.

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
PR: https://github.com/hl7ch/ch-rad-order/pull/8

**Comment by oliveregger** [comment]
with the current (not updated questionnaire) the validator gives an error:

Test
1E - 2
Location
/Bundle/entry[2]/resource/ofType(QuestionnaireResponse)/item[0]/item[0]
Description
Items of type group should not have answers

**Comment by JBleuer** [comment]
Changed to "attachment"; set cardinaltiy to 0..*

**Comment by JBleuer** [comment]
According to @ziegm changed type  from media to attachment; Questionnaire and QR changed (see above)
see also #9.
@oliveregger: Machst du das Mapping?
Question: Media would allow for metadata of the attachment; Attachment as type does not. Metadata would be nice but are not nandatory
