### ISSUE TITLE
Questionnaire: readonly fields (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#5]
ch.fhir.ig.ch-rad-order#0.1.0 /questionnaire.html

The values for the readonly fields order.title, order.type, order.category must be defined fix for the CH RAD-Order Questionnaire. It is to be discussed where this should be done (Questionnaire, QuestionnaireResponse).
This must then be described in the IG CH ORF because it affects all derived exchange formats.

Michaela Ziegler, ahdis ag

**Comment by JBleuer** [comment]
See: https://github.com/hl7ch/ch-orf/issues/31#issue-980309907

**Comment by JBleuer** [comment]
@ziegm @oliveregger 
order.title, order.type, order.category defined as:

* item[=].item[+].linkId = "order.title"
.....
* item[=].item[=].initial.valueString = "Radiologieauftrag"
=====
* item[=].item[+].linkId = "order.type"
.....
* item[=].item[=].answerValueSet = DocumentEntryTypeCode
* item[=].item[=].initial.valueCoding = DocumentEntryTypeCode#2161000195103 // Bildgebungsauftrag
=====
* item[=].item[+].linkId = "order.category"
......
* item[=].item[=].answerValueSet = DocumentEntryClassCode
* item[=].item[=].initial.valueCoding = DocumentEntryClassCode#721963009 // Untersuchungsauftrag

**Comment by JBleuer** [comment]
Removed from questionnaire; values assigned in composition; see http://build.fhir.org/ig/hl7ch/ch-orf/index.html#composition-resource

**Comment by PeroGrgic** [comment]
Issue resolved and closed.
