### ISSUE TITLE
Snomed Code 182817000 |Drug prescription (situation)| is not active anymore (but valid)

### ISSUE THREAD

**Issue by JBleuer** [hl7ch/ch-rad-order#54]
FHIR QA: Snomed Code 182817000 |Drug prescription (situation)| is not active anymore (but valid)
see also:
[Snomed sagt folgendes, eine Alternative habe ich nicht gefunden](https://confluence.ihtsdotools.org/display/RMT/SNOMED+CT+April+2022+International+Edition+-+SNOMED+International+Release+notes)

-->EHS: How to proceed?

**Comment by pjolo** [comment]
Hallo zusammen
 
Ich habe nachgeschaut in SNOMED und das Konzept 182817000 |Drug prescription (situation)| wurde durch 761938008 |Medicinal prescription record (record artifact)| und 33633005 |Prescription of drug (procedure)| ersetzt: 
 
![image](https://github.com/hl7ch/ch-rad-order/assets/87263053/39617d2d-9cc0-47e8-a0cb-eb9fdcbd8562)

 
Ich gehe davon aus, dass das Konzept 33633005 |Prescription of drug (procedure)| das ist, was wir brauchen.
LG, Pero

**Comment by JBleuer** [comment]
Ok, aendere ich soLG JuergVon meinem iPhone gesendetAm 16.04.2024 um 07:59 schrieb Patrick Jolo ***@***.***>:﻿
Hallo zusammen
Ich habe nachgeschaut in SNOMED und das Konzept 182817000 |Drug prescription (situation)| wurde durch 761938008 |Medicinal prescription record (record artifact)| und 33633005 |Prescription of drug (procedure)| ersetzt:
image.png (view on web)
Ich gehe davon aus, dass das Konzept 33633005 |Prescription of drug (procedure)| das ist, was wir brauchen.
LG, Pero

**Comment by JBleuer** [comment]
Ich habe das so ersetzt. Allerings glaube ich nicht, dass 33633005 |Prescription of drug (procedure) die Sache trifft.
In unserem Fall ist die Situation gemeint (Situation betreffend Medis, die eingenommen werden und nicht das Prozedere der Verschreibung.

**Comment by PeroGrgic** [comment]
Ich habe dieses Konzept gefunden: 1290126002 |Drug therapy with explicit context (situation)|.
Von deiner Beschreibung her denke ich, dass dieses Konzept es ziemlich gut abdeckt.
Wie siehst du das?

**Comment by JBleuer** [comment]
Changed to 1290126002 |Drug therapy with explicit context (situation); I think, this is ok.
