### ISSUE TITLE
Use CH Core base profiles

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-rad-order#59]
- Condition
   - CH RAD-Order Caveat Condition
   -  CH RAD-Order Diagnosis Condition

**Comment by ziegm** [comment]
@pjolo please review the changes: https://github.com/hl7ch/ch-rad-order/pull/60/files

**Comment by pjolo** [comment]
The adaptations are good.
I have seen that the changelog page is not linked on the home page
![image](https://github.com/hl7ch/ch-rad-order/assets/87263053/7d7960b5-4645-40c6-a756-a82ae09c9fc4)

**Comment by ziegm** [comment]
included, thanks for the hint
