### ISSUE TITLE
Questionnaire: typo (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#6]
ch.fhir.ig.ch-rad-order#0.1.0 /questionnaire.html

Typo in item 'previousResults.attachtment.title'

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
PR: https://github.com/hl7ch/ch-rad-order/pull/7

**Comment by ziegm** [comment]
obsolet aufgrund issue https://github.com/hl7ch/ch-rad-order/issues/4
