### ISSUE TITLE
Update Coverage (Michaela Zieger, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-rad-order#63]
- Adaption to the usage of the CH Core Coverage profile as parent in CH ORF: https://github.com/hl7ch/ch-orf/issues/177
- Adaption to the changes in the CS/VS Coverage Type

**Comment by ziegm** [comment]
@pjolo please review the changes:

* Update Coverage.type in example [Coverage KVG](https://build.fhir.org/ig/hl7ch/ch-rad-order/branches/issue63_coverage/Coverage-CoverageKVG.json.html)
* [changelog](https://build.fhir.org/ig/hl7ch/ch-rad-order/branches/issue63_coverage/changelog.html)

**Comment by pjolo** [comment]
The changes are good.
