### ISSUE TITLE
Use Cases (Marcel Hanselmann)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#68]
ch.fhir.ig.ch-rad-order#2.0.0-ballot /usecase-english.html

2 TBD : Insert text or remove
2.1 To be clear, replace or add Referral for Imaging
2.2 Second Opinion: To be clear, replace with "Request for second Opinion"
2.3 Externe Befundung: Translate to english (e.g. "Request for remote Reporting"). Insert details of use case
Use Case to add: Referral for radiological intervention

Marcel Hanselmann

**Comment by pjolo** [comment]
Issue was worked on in Issue #73
