### ISSUE TITLE
Caveat Renal Insufficiency Creatinine Clearance (hanselmann48@gmail.com)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#69]
ch.fhir.ig.ch-rad-order#2.0.0-ballot /Observation-CaveatRenalInsufficiencyCreatinineClearance.html

Consider using eGFR in place of Creatinine Clearance
[ https://www.swissnephrology.ch/wp/wp-content/uploads/2023/01/161121_SGN_Pocketguide_CKD_Web_A4_d_WZ.pdf ]

hanselmann48@gmail.com

**Comment by pjolo** [comment]
Profile [CH RAD-Order Glomerular Filtration Rate Observation](https://build.fhir.org/ig/hl7ch/ch-rad-order/branches/Issue69-change-caveat-renal-insufficiency-to-GFR/StructureDefinition-ch-rad-order-gfr-observation.html) added

[CH RAD-Order Caveat Condition](https://build.fhir.org/ig/hl7ch/ch-rad-order/branches/Issue69-change-caveat-renal-insufficiency-to-GFR/StructureDefinition-ch-rad-order-caveat-condition.html) change reference from creatinine clearance to GFR

[QuestionnaireRadiologyOrder ](https://build.fhir.org/ig/hl7ch/ch-rad-order/branches/Issue69-change-caveat-renal-insufficiency-to-GFR/Questionnaire-QuestionnaireRadiologyOrder.html) adjusted to GFR

[Questionnaire Form ](https://build.fhir.org/ig/hl7ch/ch-rad-order/branches/Issue69-change-caveat-renal-insufficiency-to-GFR/questionnaire-form.html) adjusted to GFR

[Module Questionnaire Caveats](https://build.fhir.org/ig/hl7ch/ch-rad-order/branches/Issue69-change-caveat-renal-insufficiency-to-GFR/Questionnaire-ch-rad-order-module-caveats.html) adjusted to GFR

[QuestionniaireResponse Radiology Order](https://build.fhir.org/ig/hl7ch/ch-rad-order/branches/Issue69-change-caveat-renal-insufficiency-to-GFR/QuestionnaireResponse-QuestionnaireResponseRadiologyOrder.html) adjusted to GFR


Map adapted [RadOrderQrToBundle](https://build.fhir.org/ig/hl7ch/ch-rad-order/branches/Issue69-change-caveat-renal-insufficiency-to-GFR/StructureMap-RadOrderQrToBundle.html) and [RadOrderQrToBundle](https://build.fhir.org/ig/hl7ch/ch-rad-order/branches/Issue69-change-caveat-renal-insufficiency-to-GFR/StructureMap-RadOrderQrToBundle.html)

[Changelog](https://build.fhir.org/ig/hl7ch/ch-rad-order/branches/Issue69-change-caveat-renal-insufficiency-to-GFR/changelog.html)

**Comment by JBleuer** [comment]
Will not be implemented as agreed with Thomas Frauenfelder and Marcel Hanselmann.
Argumentation:
Mit der Angabe der eGFR laufen wir in mehere Probleme:

1. Es gibt mehrere Berechnungseisen, schon nur bei der CKD-EPI-Formel gibt es zwei Methoden: Tatsächliche  Gewicht und Grösse vs. normierte Körperfläche 1.73 m².

2. Gemäss Laborleute müsste der Wert noch angepasst werden, je nachdem ob es sich um ein aktuelles Nierenproblem handelt oder einen Steady State.

==> Man müsste deshalb zum Wert selbst bei obligatorischer CKD-EPI-Formel noch weitere Angaben verlangen; das macht das Formular noch umfangreicher als jetzt schon.

3. Es ist wahrscheinlich, dass ein Wert (nach anderer Methode berechnet) aus einem Labor unreflektiert in den Rad-Order übernommen wird, auch wenn im Rad-Order expressis verbis CKD-EPI verlangt wird.

3. Hautfarbe ist ein problem, da Angaben wegen Datenschutzargumenten fehlen.

4. Mit Gender dürfte das mit der Zeit auch ein Problem werden (biolog. vs. legislativer Gender).

Bei den Labors gibt es hauptsächlich zwei Ansichten: eGFR geben wir ungern an, da der Wert von Angaben aus der Zuweisung berechnet wird und diese nicht überprüfbar sind vs. eGF wird gemacht, weil verlangt, auch wenn es problematisch ist.

Kurz: Wenn man die eGFR will, berechnet man sie am besten selbst, dann weiss man was man gemacht hat. Ich plädiere deshalb dafür, dass wir diesen Wert in der RAD-Order weglassen.
