### ISSUE TITLE
Extensions (Marcel Hanselmann)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#70]
ch.fhir.ig.ch-rad-order#2.0.0-ballot /extensions.html

CH RAD-Order Caveat Type occurs twice, but different URLs:
https://fhir.ch/ig/ch-rad-order/StructureDefinition-ch-rad-order-caveat-type.html
https://fhir.ch/ig/ch-rad-order/StructureDefinition-ch-rad-order-qualifier-value.html

Marcel Hanselmann

**Comment by pjolo** [comment]
This issue was resolved with issue #74
