### ISSUE TITLE
ServiceRequest.supportingInfo:previousImagingResults (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-rad-order#9]
ch.fhir.ig.ch-rad-order#0.1.0 /StructureDefinition-ch-rad-order-servicerequest.html

Actual Reference: CH RAD-Order ImagingStudy | CH RAD-Order Media
Reference may change to resource type [Binary](https://www.hl7.org/fhir/binary.html), because the Questionnaire asks for an [attachment](https://www.hl7.org/fhir/valueset-item-type.html) with binary content such as an image, PDF, etc.

Michaela Ziegler, ahdis ag

**Comment by JBleuer** [comment]
see https://github.com/hl7ch/ch-rad-order/issues/4#issuecomment-972065080. Issue therefore closed.
